# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\py\workplace\DatabaseHIT\count.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CountWindow(object):
    def setupUi(self, CountWindow):
        CountWindow.setObjectName(_fromUtf8("CountWindow"))
        CountWindow.resize(788, 777)
        self.centralWidget = QtGui.QWidget(CountWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.pushButton_by_zc = QtGui.QPushButton(self.centralWidget)
        self.pushButton_by_zc.setGeometry(QtCore.QRect(240, 580, 121, 51))
        self.pushButton_by_zc.setObjectName(_fromUtf8("pushButton_by_zc"))
        self.pushButton_by_wh = QtGui.QPushButton(self.centralWidget)
        self.pushButton_by_wh.setGeometry(QtCore.QRect(420, 580, 121, 51))
        self.pushButton_by_wh.setObjectName(_fromUtf8("pushButton_by_wh"))
        self.pushButton_by_bm = QtGui.QPushButton(self.centralWidget)
        self.pushButton_by_bm.setGeometry(QtCore.QRect(590, 580, 121, 51))
        self.pushButton_by_bm.setObjectName(_fromUtf8("pushButton_by_bm"))
        self.textEdit_input = QtGui.QTextEdit(self.centralWidget)
        self.textEdit_input.setGeometry(QtCore.QRect(60, 580, 121, 51))
        self.textEdit_input.setObjectName(_fromUtf8("textEdit_input"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(30, 80, 331, 51))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Agency FB"))
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.tableWidget = QtGui.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 170, 771, 341))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(31)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(25, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(26, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(27, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(28, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(29, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(30, item)
        CountWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(CountWindow)
        QtCore.QMetaObject.connectSlotsByName(CountWindow)

    def retranslateUi(self, CountWindow):
        CountWindow.setWindowTitle(_translate("CountWindow", "CountWindow", None))
        self.pushButton_by_zc.setText(_translate("CountWindow", "统计职称", None))
        self.pushButton_by_wh.setText(_translate("CountWindow", "统计文化", None))
        self.pushButton_by_bm.setText(_translate("CountWindow", "统计部门", None))
        self.label.setText(_translate("CountWindow", "当前公司总人数：", None))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("CountWindow", "职工编码", None))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("CountWindow", "姓名", None))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("CountWindow", "性别", None))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("CountWindow", "民族", None))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("CountWindow", "出生年月", None))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("CountWindow", "婚姻状况", None))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("CountWindow", "文化程度", None))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("CountWindow", "健康状况", None))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("CountWindow", "政治面貌", None))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("CountWindow", "职称", None))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("CountWindow", "籍贯", None))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("CountWindow", "身份证号码", None))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("CountWindow", "毕业学校", None))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("CountWindow", "专业或特长", None))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("CountWindow", "户口所在地", None))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("CountWindow", "户口性质", None))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("CountWindow", "现住址", None))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("CountWindow", "职务", None))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("CountWindow", "工种名", None))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("CountWindow", "何时技术培训", None))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("CountWindow", "何时奖励和处分", None))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("CountWindow", "需要说明问题", None))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("CountWindow", "填表人签名", None))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("CountWindow", "填表日期", None))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("CountWindow", "公司审查意见", None))
        item = self.tableWidget.horizontalHeaderItem(25)
        item.setText(_translate("CountWindow", "审查日期", None))
        item = self.tableWidget.horizontalHeaderItem(26)
        item.setText(_translate("CountWindow", "人员性质", None))
        item = self.tableWidget.horizontalHeaderItem(27)
        item.setText(_translate("CountWindow", "入常时间", None))
        item = self.tableWidget.horizontalHeaderItem(28)
        item.setText(_translate("CountWindow", "人员状态", None))
        item = self.tableWidget.horizontalHeaderItem(29)
        item.setText(_translate("CountWindow", "备注", None))
        item = self.tableWidget.horizontalHeaderItem(30)
        item.setText(_translate("CountWindow", "部门", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    CountWindow = QtGui.QMainWindow()
    ui = Ui_CountWindow()
    ui.setupUi(CountWindow)
    CountWindow.show()
    sys.exit(app.exec_())

