# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'H:\py\workplace\DatabaseHIT\profile.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ProfileWindow(object):
    def setupUi(self, ProfileWindow):
        ProfileWindow.setObjectName(_fromUtf8("ProfileWindow"))
        ProfileWindow.resize(800, 827)
        self.centralWidget = QtGui.QWidget(ProfileWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.label_21 = QtGui.QLabel(self.centralWidget)
        self.label_21.setGeometry(QtCore.QRect(40, 350, 111, 31))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_9 = QtGui.QLabel(self.centralWidget)
        self.label_9.setGeometry(QtCore.QRect(540, 110, 71, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_30 = QtGui.QLabel(self.centralWidget)
        self.label_30.setGeometry(QtCore.QRect(40, 580, 101, 31))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_10 = QtGui.QLabel(self.centralWidget)
        self.label_10.setGeometry(QtCore.QRect(40, 160, 71, 31))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_8 = QtGui.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(540, 70, 71, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(300, 30, 71, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_xm2 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_xm2.setGeometry(QtCore.QRect(380, 750, 113, 31))
        self.lineEdit_xm2.setObjectName(_fromUtf8("lineEdit_xm2"))
        self.lineEdit_jspx = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_jspx.setGeometry(QtCore.QRect(560, 300, 171, 31))
        self.lineEdit_jspx.setObjectName(_fromUtf8("lineEdit_jspx"))
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(300, 70, 71, 31))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_22 = QtGui.QLabel(self.centralWidget)
        self.label_22.setGeometry(QtCore.QRect(410, 350, 111, 31))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.comboBox_xb = QtGui.QComboBox(self.centralWidget)
        self.comboBox_xb.setGeometry(QtCore.QRect(130, 110, 111, 31))
        self.comboBox_xb.setObjectName(_fromUtf8("comboBox_xb"))
        self.lineEdit_brgx1 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_brgx1.setGeometry(QtCore.QRect(140, 700, 113, 31))
        self.lineEdit_brgx1.setObjectName(_fromUtf8("lineEdit_brgx1"))
        self.lineEdit_sfzh = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_sfzh.setGeometry(QtCore.QRect(130, 240, 113, 31))
        self.lineEdit_sfzh.setObjectName(_fromUtf8("lineEdit_sfzh"))
        self.label_27 = QtGui.QLabel(self.centralWidget)
        self.label_27.setGeometry(QtCore.QRect(40, 530, 101, 31))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_38 = QtGui.QLabel(self.centralWidget)
        self.label_38.setGeometry(QtCore.QRect(540, 750, 101, 31))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.label_35 = QtGui.QLabel(self.centralWidget)
        self.label_35.setGeometry(QtCore.QRect(540, 700, 101, 31))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.comboBox_zcbm = QtGui.QComboBox(self.centralWidget)
        self.comboBox_zcbm.setGeometry(QtCore.QRect(130, 160, 111, 31))
        self.comboBox_zcbm.setObjectName(_fromUtf8("comboBox_zcbm"))
        self.label_16 = QtGui.QLabel(self.centralWidget)
        self.label_16.setGeometry(QtCore.QRect(540, 160, 71, 31))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_ryxz = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_ryxz.setGeometry(QtCore.QRect(140, 530, 113, 31))
        self.lineEdit_ryxz.setObjectName(_fromUtf8("lineEdit_ryxz"))
        self.lineEdit_csny = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_csny.setGeometry(QtCore.QRect(390, 70, 113, 31))
        self.lineEdit_csny.setObjectName(_fromUtf8("lineEdit_csny"))
        self.label_17 = QtGui.QLabel(self.centralWidget)
        self.label_17.setGeometry(QtCore.QRect(540, 200, 71, 31))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 71, 31))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton_update = QtGui.QPushButton(self.centralWidget)
        self.pushButton_update.setGeometry(QtCore.QRect(540, 600, 101, 51))
        self.pushButton_update.setObjectName(_fromUtf8("pushButton_update"))
        self.label_28 = QtGui.QLabel(self.centralWidget)
        self.label_28.setGeometry(QtCore.QRect(300, 530, 101, 31))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_23 = QtGui.QLabel(self.centralWidget)
        self.label_23.setGeometry(QtCore.QRect(40, 410, 81, 31))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_25 = QtGui.QLabel(self.centralWidget)
        self.label_25.setGeometry(QtCore.QRect(40, 470, 101, 31))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.comboBox_zzmm = QtGui.QComboBox(self.centralWidget)
        self.comboBox_zzmm.setGeometry(QtCore.QRect(650, 110, 111, 31))
        self.comboBox_zzmm.setObjectName(_fromUtf8("comboBox_zzmm"))
        self.label_33 = QtGui.QLabel(self.centralWidget)
        self.label_33.setGeometry(QtCore.QRect(40, 700, 81, 31))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_20 = QtGui.QLabel(self.centralWidget)
        self.label_20.setGeometry(QtCore.QRect(410, 300, 101, 31))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_29 = QtGui.QLabel(self.centralWidget)
        self.label_29.setGeometry(QtCore.QRect(540, 530, 101, 31))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.lineEdit_xm1 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_xm1.setGeometry(QtCore.QRect(380, 700, 113, 31))
        self.lineEdit_xm1.setObjectName(_fromUtf8("lineEdit_xm1"))
        self.comboBox_bmbm = QtGui.QComboBox(self.centralWidget)
        self.comboBox_bmbm.setGeometry(QtCore.QRect(400, 580, 111, 31))
        self.comboBox_bmbm.setObjectName(_fromUtf8("comboBox_bmbm"))
        self.lineEdit_mz = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_mz.setGeometry(QtCore.QRect(390, 30, 113, 31))
        self.lineEdit_mz.setObjectName(_fromUtf8("lineEdit_mz"))
        self.label_24 = QtGui.QLabel(self.centralWidget)
        self.label_24.setGeometry(QtCore.QRect(410, 410, 81, 31))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_18 = QtGui.QLabel(self.centralWidget)
        self.label_18.setGeometry(QtCore.QRect(540, 240, 71, 31))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_31 = QtGui.QLabel(self.centralWidget)
        self.label_31.setGeometry(QtCore.QRect(300, 590, 101, 31))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lineEdit_byxx = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_byxx.setGeometry(QtCore.QRect(390, 160, 113, 31))
        self.lineEdit_byxx.setObjectName(_fromUtf8("lineEdit_byxx"))
        self.lineEdit_tbrqm = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_tbrqm.setGeometry(QtCore.QRect(180, 410, 171, 31))
        self.lineEdit_tbrqm.setObjectName(_fromUtf8("lineEdit_tbrqm"))
        self.label_37 = QtGui.QLabel(self.centralWidget)
        self.label_37.setGeometry(QtCore.QRect(300, 750, 81, 31))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.comboBox_whcd = QtGui.QComboBox(self.centralWidget)
        self.comboBox_whcd.setGeometry(QtCore.QRect(650, 30, 111, 31))
        self.comboBox_whcd.setObjectName(_fromUtf8("comboBox_whcd"))
        self.label_13 = QtGui.QLabel(self.centralWidget)
        self.label_13.setGeometry(QtCore.QRect(300, 160, 71, 31))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.lineEdit_jg = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_jg.setGeometry(QtCore.QRect(130, 200, 113, 31))
        self.lineEdit_jg.setObjectName(_fromUtf8("lineEdit_jg"))
        self.label_36 = QtGui.QLabel(self.centralWidget)
        self.label_36.setGeometry(QtCore.QRect(40, 750, 81, 31))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.lineEdit_smwt = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_smwt.setGeometry(QtCore.QRect(560, 350, 171, 31))
        self.lineEdit_smwt.setObjectName(_fromUtf8("lineEdit_smwt"))
        self.lineEdit_hzgz2 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_hzgz2.setGeometry(QtCore.QRect(660, 750, 113, 31))
        self.lineEdit_hzgz2.setObjectName(_fromUtf8("lineEdit_hzgz2"))
        self.lineEdit_scrq = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_scrq.setGeometry(QtCore.QRect(560, 470, 171, 31))
        self.lineEdit_scrq.setObjectName(_fromUtf8("lineEdit_scrq"))
        self.lineEdit_xzz = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_xzz.setGeometry(QtCore.QRect(650, 200, 113, 31))
        self.lineEdit_xzz.setObjectName(_fromUtf8("lineEdit_xzz"))
        self.label_19 = QtGui.QLabel(self.centralWidget)
        self.label_19.setGeometry(QtCore.QRect(40, 300, 71, 31))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_hzgz1 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_hzgz1.setGeometry(QtCore.QRect(660, 700, 113, 31))
        self.lineEdit_hzgz1.setObjectName(_fromUtf8("lineEdit_hzgz1"))
        self.lineEdit_tbrq = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_tbrq.setGeometry(QtCore.QRect(560, 410, 171, 31))
        self.lineEdit_tbrq.setObjectName(_fromUtf8("lineEdit_tbrq"))
        self.label_11 = QtGui.QLabel(self.centralWidget)
        self.label_11.setGeometry(QtCore.QRect(40, 200, 71, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.lineEdit_jkzk = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_jkzk.setGeometry(QtCore.QRect(650, 70, 113, 31))
        self.lineEdit_jkzk.setObjectName(_fromUtf8("lineEdit_jkzk"))
        self.comboBox_hyzk = QtGui.QComboBox(self.centralWidget)
        self.comboBox_hyzk.setGeometry(QtCore.QRect(390, 110, 111, 31))
        self.comboBox_hyzk.setObjectName(_fromUtf8("comboBox_hyzk"))
        self.lineEdit_jlcf = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_jlcf.setGeometry(QtCore.QRect(180, 350, 171, 31))
        self.lineEdit_jlcf.setObjectName(_fromUtf8("lineEdit_jlcf"))
        self.lineEdit_zw = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_zw.setGeometry(QtCore.QRect(650, 240, 113, 31))
        self.lineEdit_zw.setObjectName(_fromUtf8("lineEdit_zw"))
        self.label_7 = QtGui.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(540, 30, 101, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_gzm = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_gzm.setGeometry(QtCore.QRect(180, 300, 171, 31))
        self.lineEdit_gzm.setObjectName(_fromUtf8("lineEdit_gzm"))
        self.lineEdit_zgbm = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_zgbm.setGeometry(QtCore.QRect(130, 30, 113, 31))
        self.lineEdit_zgbm.setObjectName(_fromUtf8("lineEdit_zgbm"))
        self.lineEdit_ryzt = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_ryzt.setGeometry(QtCore.QRect(640, 530, 113, 31))
        self.lineEdit_ryzt.setObjectName(_fromUtf8("lineEdit_ryzt"))
        self.label_12 = QtGui.QLabel(self.centralWidget)
        self.label_12.setGeometry(QtCore.QRect(40, 240, 81, 31))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lineEdit_zytc = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_zytc.setGeometry(QtCore.QRect(390, 200, 113, 31))
        self.lineEdit_zytc.setObjectName(_fromUtf8("lineEdit_zytc"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 71, 31))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(40, 70, 71, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_15 = QtGui.QLabel(self.centralWidget)
        self.label_15.setGeometry(QtCore.QRect(300, 240, 81, 31))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_26 = QtGui.QLabel(self.centralWidget)
        self.label_26.setGeometry(QtCore.QRect(410, 470, 101, 31))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lineEdit_brgx2 = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_brgx2.setGeometry(QtCore.QRect(140, 750, 113, 31))
        self.lineEdit_brgx2.setObjectName(_fromUtf8("lineEdit_brgx2"))
        self.label_32 = QtGui.QLabel(self.centralWidget)
        self.label_32.setGeometry(QtCore.QRect(40, 650, 351, 31))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(300, 110, 71, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_34 = QtGui.QLabel(self.centralWidget)
        self.label_34.setGeometry(QtCore.QRect(300, 700, 81, 31))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.lineEdit_hkszd = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_hkszd.setGeometry(QtCore.QRect(390, 240, 113, 31))
        self.lineEdit_hkszd.setObjectName(_fromUtf8("lineEdit_hkszd"))
        self.lineEdit_bz = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_bz.setGeometry(QtCore.QRect(140, 580, 113, 31))
        self.lineEdit_bz.setObjectName(_fromUtf8("lineEdit_bz"))
        self.comboBox_hkxz = QtGui.QComboBox(self.centralWidget)
        self.comboBox_hkxz.setGeometry(QtCore.QRect(650, 160, 111, 31))
        self.comboBox_hkxz.setObjectName(_fromUtf8("comboBox_hkxz"))
        self.lineEdit_gsyj = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_gsyj.setGeometry(QtCore.QRect(180, 470, 171, 31))
        self.lineEdit_gsyj.setObjectName(_fromUtf8("lineEdit_gsyj"))
        self.label_14 = QtGui.QLabel(self.centralWidget)
        self.label_14.setGeometry(QtCore.QRect(300, 200, 81, 31))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lineEdit_rcsj = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_rcsj.setGeometry(QtCore.QRect(400, 530, 113, 31))
        self.lineEdit_rcsj.setObjectName(_fromUtf8("lineEdit_rcsj"))
        self.lineEdit_xm = QtGui.QLineEdit(self.centralWidget)
        self.lineEdit_xm.setGeometry(QtCore.QRect(130, 70, 113, 31))
        self.lineEdit_xm.setObjectName(_fromUtf8("lineEdit_xm"))
        self.pushButton_delete = QtGui.QPushButton(self.centralWidget)
        self.pushButton_delete.setGeometry(QtCore.QRect(660, 600, 101, 51))
        self.pushButton_delete.setObjectName(_fromUtf8("pushButton_delete"))
        ProfileWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(ProfileWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfileWindow)

    def retranslateUi(self, ProfileWindow):
        ProfileWindow.setWindowTitle(_translate("ProfileWindow", "ProfileWindow", None))
        self.label_21.setText(_translate("ProfileWindow", "何种奖励和处分", None))
        self.label_9.setText(_translate("ProfileWindow", "政治面貌", None))
        self.label_30.setText(_translate("ProfileWindow", "备注", None))
        self.label_10.setText(_translate("ProfileWindow", "职称编码", None))
        self.label_8.setText(_translate("ProfileWindow", "健康状况", None))
        self.label_4.setText(_translate("ProfileWindow", "民族", None))
        self.label_5.setText(_translate("ProfileWindow", "出生年月", None))
        self.label_22.setText(_translate("ProfileWindow", "需要说明问题", None))
        self.label_27.setText(_translate("ProfileWindow", "人员性质", None))
        self.label_38.setText(_translate("ProfileWindow", "从事何种工作", None))
        self.label_35.setText(_translate("ProfileWindow", "从事何种工作", None))
        self.label_16.setText(_translate("ProfileWindow", "户口性质", None))
        self.label_17.setText(_translate("ProfileWindow", "现在住址", None))
        self.label.setText(_translate("ProfileWindow", "职工编码", None))
        self.pushButton_update.setText(_translate("ProfileWindow", "更新", None))
        self.label_28.setText(_translate("ProfileWindow", "入厂时间", None))
        self.label_23.setText(_translate("ProfileWindow", "填表人签名", None))
        self.label_25.setText(_translate("ProfileWindow", "公司审查意见", None))
        self.label_33.setText(_translate("ProfileWindow", "与本人关系", None))
        self.label_20.setText(_translate("ProfileWindow", "何种技术培训", None))
        self.label_29.setText(_translate("ProfileWindow", "人员状态", None))
        self.label_24.setText(_translate("ProfileWindow", "填表日期", None))
        self.label_18.setText(_translate("ProfileWindow", "职务", None))
        self.label_31.setText(_translate("ProfileWindow", "部门编码", None))
        self.label_37.setText(_translate("ProfileWindow", "姓名", None))
        self.label_13.setText(_translate("ProfileWindow", "毕业学校", None))
        self.label_36.setText(_translate("ProfileWindow", "与本人关系", None))
        self.label_19.setText(_translate("ProfileWindow", "工种名", None))
        self.label_11.setText(_translate("ProfileWindow", "籍贯", None))
        self.label_7.setText(_translate("ProfileWindow", "文化程度编码", None))
        self.label_12.setText(_translate("ProfileWindow", "身份证号码", None))
        self.label_3.setText(_translate("ProfileWindow", "性别", None))
        self.label_2.setText(_translate("ProfileWindow", "姓名", None))
        self.label_15.setText(_translate("ProfileWindow", "户口所在地", None))
        self.label_26.setText(_translate("ProfileWindow", "审查日期", None))
        self.label_32.setText(_translate("ProfileWindow", "-----------主要成员与社会关系---------------", None))
        self.label_6.setText(_translate("ProfileWindow", "婚姻状况", None))
        self.label_34.setText(_translate("ProfileWindow", "姓名", None))
        self.label_14.setText(_translate("ProfileWindow", "专业或特长", None))
        self.pushButton_delete.setText(_translate("ProfileWindow", "删除", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    ProfileWindow = QtGui.QMainWindow()
    ui = Ui_ProfileWindow()
    ui.setupUi(ProfileWindow)
    ProfileWindow.show()
    sys.exit(app.exec_())

